"use client";

// HAND-MAINTAINED (not generated by .duplicator/tools/convert.mjs).
// Corner-anchored header in the style of tengilemalamala.com: "Reserve" left, logo centre, "Menu" right.
// The menu opens a full-screen overlay with large, staggered links. The header slides away on scroll down and
// back on scroll up.

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";

type LenisLike = { stop: () => void; start: () => void };
const lenis = () => (window as unknown as { __lenis?: LenisLike }).__lenis;

const PRIMARY: { href: string; label: string }[] = [
  { href: "/", label: "Home" },
  { href: "/services/", label: "Services" },
  { href: "/menu/", label: "Menu & Pricing" },
  { href: "/locations/", label: "Locations" },
  { href: "/blog/", label: "Journal" },
  { href: "/salon-policy/", label: "Salon Policy" },
];

const SERVICES: { href: string; label: string }[] = [
  { href: "/services/acrylic-nails/", label: "Acrylic Nails" },
  { href: "/services/builder-gel-nails/", label: "Builder Gel Nails" },
  { href: "/services/dip-powder-nails/", label: "Dip Powder / SNS" },
  { href: "/services/gel-x-nails/", label: "Aprés Gel-X" },
  { href: "/services/nail-art/", label: "Custom Nail Art" },
  { href: "/services/spa-pedicures/", label: "Spa Pedicures" },
  { href: "/services/organic-deluxe-pedicure/", label: "Organic Spa Pedicure" },
  { href: "/services/deluxe-pedicure/", label: "Deluxe Pedicure" },
  { href: "/services/pearl-spa-pedicure/", label: "Pearl Spa Pedicure" },
  { href: "/services/jelly-spa-pedicure/", label: "Jelly Spa Pedicure" },
  { href: "/services/cbd-rejuvenating-pedicure/", label: "CBD Experience Pedicure" },
  { href: "/services/24k-gold-enchantment-pedicure/", label: "Gold Enchantment Pedicure" },
];

const SECONDARY: { href: string; label: string }[] = [
  { href: "/#reviews", label: "Reviews" },
  { href: "/#why", label: "Why Element" },
  { href: "/#visit", label: "Visit" },
  { href: "/about-us/", label: "About" },
  { href: "/faqs/", label: "FAQs" },
  { href: "/contact/", label: "Contact" },
];

const norm = (p: string) => (p.endsWith("/") ? p : p + "/");

export default function Header() {
  const pathname = norm(usePathname() || "/");
  // The menu is open for the route it was opened on, so it closes by itself when the route changes.
  const [openPath, setOpenPath] = useState<string | null>(null);
  const open = openPath === pathname;
  const setOpen = useCallback((v: boolean | ((prev: boolean) => boolean)) => {
    setOpenPath((prev) => ((typeof v === "function" ? v(prev === pathname) : v) ? pathname : null));
  }, [pathname]);
  const [hidden, setHidden] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);
  const buttonRef = useRef<HTMLButtonElement>(null);
  const lastY = useRef(0);

  const current = (href: string) => (!href.includes("#") && norm(href) === pathname ? "page" : undefined);

  const close = useCallback((returnFocus = true) => {
    setOpen(false);
    if (returnFocus) buttonRef.current?.focus();
  }, [setOpen]);

  // Hide on scroll down, show on scroll up.
  useEffect(() => {
    const onScroll = () => {
      const y = window.scrollY;
      setScrolled(y > 8);
      if (Math.abs(y - lastY.current) > 6) {
        setHidden(y > 160 && y > lastY.current);
        lastY.current = y;
      }
    };
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  // Menu open: lock page scroll (also with Lenis), focus the first link, close on Escape.
  useEffect(() => {
    if (!open) return;
    lenis()?.stop();
    const previous = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    const first = menuRef.current?.querySelector<HTMLElement>("a");
    const t = window.setTimeout(() => first?.focus({ preventScroll: true }), 350);
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") close();
      if (e.key !== "Tab" || !menuRef.current) return;
      const focusables = [buttonRef.current, ...Array.from(menuRef.current.querySelectorAll<HTMLElement>("a, button"))].filter(Boolean) as HTMLElement[];
      const firstEl = focusables[0];
      const lastEl = focusables[focusables.length - 1];
      if (e.shiftKey && document.activeElement === firstEl) { e.preventDefault(); lastEl.focus(); }
      else if (!e.shiftKey && document.activeElement === lastEl) { e.preventDefault(); firstEl.focus(); }
    };
    document.addEventListener("keydown", onKey);
    return () => {
      window.clearTimeout(t);
      document.removeEventListener("keydown", onKey);
      document.body.style.overflow = previous;
      lenis()?.start();
    };
  }, [open, close, setOpen]);

  let step = 0;
  const delay = () => ({ "--i": step++ }) as React.CSSProperties;

  return (
    <>
      <header className={`ed-header${hidden && !open ? " is-hidden" : ""}${scrolled ? " is-scrolled" : ""}${open ? " is-open" : ""}`}>
        <a className="ed-reserve" href="/booking/">
          Reserve
        </a>
        <Link className="ed-logo" href="/" aria-label="Element Nail Bar 16th Street home" aria-current={current("/")}>
          <img src="/media/images/element-nail-bar-logo-144.webp" alt="Element Nail Bar" width={144} height={144} />
        </Link>
        <button
          ref={buttonRef}
          type="button"
          className="ed-menu-button"
          aria-expanded={open}
          aria-controls="ed-menu"
          onClick={() => setOpen((v) => !v)}
        >
          <span className="ed-menu-label" data-open="Close" data-closed="Menu" />
          <span className="visually-hidden">{open ? "Close menu" : "Open menu"}</span>
        </button>
      </header>

      <div id="ed-menu" ref={menuRef} className={`ed-menu${open ? " is-open" : ""}`} role="dialog" aria-modal="true" aria-label="Site menu" aria-hidden={!open} inert={!open}>
        <div className="ed-menu-inner">
          <nav className="ed-menu-primary" aria-label="Main navigation">
            <ul>
              {PRIMARY.map((l) => (
                <li key={l.href}>
                  <Link href={l.href} aria-current={current(l.href)} onClick={() => setOpen(false)}>
                    <span className="ed-menu-mask">
                      <span style={delay()}>{l.label}</span>
                    </span>
                  </Link>
                </li>
              ))}
            </ul>
          </nav>
          <div className="ed-menu-side">
            <nav aria-label="Services">
              <p className="ed-menu-title">Services</p>
              <ul className="ed-menu-services">
                {SERVICES.map((l) => (
                  <li key={l.href} style={delay()}>
                    <Link href={l.href} aria-current={current(l.href)} onClick={() => setOpen(false)}>
                      {l.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </nav>
            <nav aria-label="More">
              <p className="ed-menu-title">More</p>
              <ul className="ed-menu-more">
                {SECONDARY.map((l) => (
                  <li key={l.href} style={delay()}>
                    <Link href={l.href} onClick={() => setOpen(false)}>
                      {l.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </nav>
            <div className="ed-menu-contact" style={delay()}>
              <a className="button brass" href="/booking/">
                Reserve now
              </a>
              <p>
                6022 N 16th St, Phoenix, AZ 85016
                <br />
                <a href="tel:+16026075686">602-607-5686</a>
                <br />
                Mon–Sat 9:30–7 · Sun 10–5
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
